### ISSUE TITLE
crash when switching devices

### ISSUE THREAD

**Issue by migizi** [Wooza/ProspectTogether#1]
I have multiple computers and when I switch to the one that wasn't the original I get the following error.. What I mean is I have a laptop that works just fine when I connect to the server and doesn't crash. When I log into my Steam Deck it crashes unless I disable the mod. I think there is data missing from the server save/send when a user switches devices.

`7/2/2023 11:11:54 AM: Critical error occurred in the following mod: prospecttogether@1.0.0
Loaded Mods: buzzwords@1.3.0, HangingOilLamps@1.0.1, meteoricexpansion@1.2.4, game@1.18.6, animalcages@2.1.5, egocaribautomapmarkers@2.6.0, betterfirepit@1.1.1, carryon@1.2.0, commonlib@2.1.1, fixhandbookclutter@1.0.5, naturalnight@2.0.0, prospecttogether@1.0.0, statushud@1.3.1, temporalstormtimer@1.1.0, creative@1.18.6, survival@1.18.6, accessibilitytweaks@3.3.2, playercorpse@1.7.1, xinvtweaks@1.5.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProspectTogether.Client.ProspectorOverlayLayer.GuiDialogWorldMapOpenPatch.Postfix(EnumDialogType type) in D:\a\ProspectTogether\ProspectTogether\src\Client\ProspectorOverlayLayer.cs:line 395
   at Vintagestory.GameContent.WorldMapManager.ToggleMap(EnumDialogType asType) in C:\Users\Tyron\Documents\vintagestory\game-net7\VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 299
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in C:\Users\Tyron\Documents\vintagestory\game-net7\VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 180
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\ClientEventAPI.cs:line 348
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\Startup.cs:line 1010
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 73
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 300
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 127
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "/home/deck/.config/VintagestoryDataNet7/Logs/client-crash.txt"
`

**Comment by Wooza** [comment]
Thanks for your feedback. 

I don't think that missing data should be the problem here, as the mod automatically syncs all clients with the server, so your steam deck should receive the all data that is stored on the server.

From the log message I can see that you are running the unstable .net7 build. Do you also run this version on your laptop? I haven't tested the mod on the new .net7 build yet, but there might be a few technical changes that I have to make, so that this mod works with the new version.

**Comment by migizi** [comment]
I think the issue is actually limited to the Steam Deck itself. I have this mod running on a .Net7 server along with 2 other laptops. They work just fine. There is something up with how the Steam Deck is built or the age of some of the libraries that are causing issues. I was able to get past the error by using an unstable daily build of .Net7 but I'm still researching the issues. For now I think this can be closed as it's only limited to the Steam Deck and no other Linux clients/servers.

**Comment by Wooza** [comment]
Thanks for coming back and posting this information. I'm going to close this for now.
