### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by caucow** [Wooza/ProspectTogether#7]
Going to be resurrecting #1 here for different reasons.
I was crashing with this stacktrace for a while in 1.18.5 when trying to update a world and resolved to just wait for 1.19.
Updating in 1.19, everything went smoothly, I switched between a few worlds including the one that was previously problematic, and had been playing on and off for hours before the problem started.

While I was in the singleplayer world, an (unrelated) crash occurred (iirc it was driver related rather than game), and since then I have not been able to open that world with ProspectTogether enabled.

Can provide configs/worldmaps (if you can tell me which one/how to find it, I haven't figured out how to get UID from a world) or a download for the world if needed for debugging.

```
Running on 64 bit Windows 10.0.19045.0 with 32640 MB RAM
Game Version: v1.19.1 (Stable)
1/24/2024 10:31:01 AM: Critical error occurred in the following mod: prospecttogether@1.3.0-rc.3
Loaded Mods: arrowsstayaround@1.0.0, fixroads@1.3.1, glowingarrows@1.2.0, guicompositesettingsex@1.1.0, layoftheland@1.0.0, moreicons@1.1.0, playerlist@1.6.0, game@1.19.1, alloycalculator@1.0.0, betterfirepit@1.1.3, bodyheatbar@1.0.1, carryon@1.7.0-pre.3, commonlib@2.3.2, deathwaypoints@1.0.3, easylightlevels@1.0.3, extrainfo@1.7.0, farmlanddropssoil@1.4.0, hudclock@3.4.0, medievalexpansion@3.13.0, nemi@1.1.0, petai@2.2.1, pixelwaypoints@1.0.0, prospecttogether@1.3.0-rc.3, resmeltableslight@1.0.0, simplestep@1.1.0, temporalprospector@1.0.1, temporalstormtimer@1.1.1, creative@1.19.1, vsimgui@0.3.3, survival@1.19.1, waypointcolours@1.1.1, waypointtogether@1.0.1, woodchests@1.1.0, workbenchexpansion@1.8.0, worldconfiggui@1.0.1, configlib@0.3.3, em@2.5.0-pre.1, extraoverlays@1.4.0, feverstonehorses@1.6.0-rc.2, pickupfast@1.0.2, simplewinddirection@1.0.2, stonequarry@3.2.1, treetapping@1.0.0, bricklayers@2.5.0-pre.2, statushudcont@2.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProspectTogether.Client.ProspectorOverlayLayer.GuiDialogWorldMapOpenPatch.Postfix(EnumDialogType type) in D:\a\ProspectTogether\ProspectTogether\src\Client\ProspectorOverlayLayer.cs:line 430
   at Vintagestory.GameContent.GuiDialogWorldMap.Open_Patch2(GuiDialogWorldMap this, EnumDialogType type)
   at Vintagestory.GameContent.WorldMapManager.ToggleMap(EnumDialogType asType) in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 306
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 220
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 372
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1040
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
   ```

**Comment by Wooza** [comment]
Hi @caucow

I just did some testing. I was able to reproduce this error after making the config for the current world invalid.
You should have a log entry in `Logs/client-main.txt` telling you what went wrong. In my case I put invalid json data in the config file (`ProspectTogetherClient-3e7dde45-b410-431d-b447-625d07b048a6.json`) and got the following error in the log:

```
24.1.2024 21:49:19 [Error] ProspectTogetherClient-3e7dde45-b410-431d-b447-625d07b048a6: Failed loading modconfig file at 'ModConfig/ProspectTogetherClient-3e7dde45-b410-431d-b447-625d07b048a6.json', with an error of 'Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got d. Path '', line 1, position 2.
   at Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.Common.APIBase.LoadModConfig[T](String filename) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\APIBase.cs:line 102
   at Foundation.ModConfig.ApiExtensions.LoadOrCreateConfig[TModConfig](ICoreAPI api, String filename, Boolean required) in D:\a\ProspectTogether\ProspectTogether\src\Foundation\ModConfig\ApiExtensions.cs:line 32'! Stopping...
```
So from there you should be able to identify the corrupt config file and either fix the error by hand or delete the file, in which case the mod will create a new default config. I hope this solves your problem.

**Comment by caucow** [comment]
So it seems the error was not in the config, but in the prospecting map data. I'm guessing the first crash somehow resulted in the map data being deleted, so the old prospectorInfo file was copied in place of the missing PT file and failed while attempting to migrate (no "Values" array, only a "Message" string). Then due to the error it never registered the PT map layer and... NPE

The file at fault:
[bad_prospectTogetherClient.json](https://github.com/Wooza/ProspectTogether/files/14044363/bad_prospectTogetherClient.json)

All logs relevant to PT from client-main:

```Log
24.1.2024 16:12:39 [Error] Failed to migrate prospecting data file at 'C:\Users\caucow\AppData\Roaming\VintagestoryData\ModData\3b8a8084-d50f-4b0e-857c-611f5c4fd66f\prospectTogetherClient.json', with an error of 'System.NullReferenceException: Object reference not set to an instance of an object.
   at ProspectTogether.ProspectTogetherModSystem.MigrateSerializationFormatToV1(String filename, ICoreAPI api) in D:\a\ProspectTogether\ProspectTogether\src\ProspectorTogetherModSystem.cs:line 128'! Either delete that file or check what is causing the problem.
24.1.2024 16:12:39 [Error] [prospecttogether] An exception was thrown when trying to start the mod:
24.1.2024 16:12:39 [Error] [prospecttogether] Exception: Object reference not set to an instance of an object.
   at ProspectTogether.ProspectTogetherModSystem.MigrateSerializationFormatToV1(String filename, ICoreAPI api) in D:\a\ProspectTogether\ProspectTogether\src\ProspectorTogetherModSystem.cs:line 128
   at ProspectTogether.ProspectTogetherModSystem.StartClientSide(ICoreClientAPI api) in D:\a\ProspectTogether\ProspectTogether\src\ProspectorTogetherModSystem.cs:line 46
   at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in VintagestoryLib\Common\API\ModLoader.cs:line 654
24.1.2024 16:12:39 [Error] Failed to start system ProspectTogether.ProspectTogetherModSystem

...

1/24/2024 4:12:41 PM: Critical error occurred in the following mod: prospecttogether@1.3.0-rc.3
Loaded Mods: arrowsstayaround@1.0.0, fixroads@1.3.1, glowingarrows@1.2.0, guicompositesettingsex@1.1.0, layoftheland@1.0.0, moreicons@1.1.0, playerlist@1.6.0, game@1.19.1, alloycalculator@1.0.0, betterfirepit@1.1.3, bodyheatbar@1.0.1, carryon@1.7.0-pre.3, commonlib@2.3.2, deathwaypoints@1.0.3, easylightlevels@1.0.3, extrainfo@1.7.0, farmlanddropssoil@1.4.0, hudclock@3.4.0, medievalexpansion@3.13.0, nemi@1.1.0, petai@2.2.1, pixelwaypoints@1.0.0, prospecttogether@1.3.0-rc.3, resmeltableslight@1.0.0, simplestep@1.1.0, temporalprospector@1.0.1, temporalstormtimer@1.1.1, creative@1.19.1, vsimgui@0.3.3, survival@1.19.1, waypointcolours@1.1.1, waypointtogether@1.0.1, woodchests@1.1.0, workbenchexpansion@1.8.0, worldconfiggui@1.0.1, configlib@0.3.3, em@2.5.0-pre.1, extraoverlays@1.4.0, feverstonehorses@1.6.0-rc.2, pickupfast@1.0.2, simplewinddirection@1.0.2, stonequarry@3.2.1, treetapping@1.0.0, bricklayers@2.5.0-pre.2, statushudcont@2.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProspectTogether.Client.ProspectorOverlayLayer.GuiDialogWorldMapOpenPatch.Postfix(EnumDialogType type) in D:\a\ProspectTogether\ProspectTogether\src\Client\ProspectorOverlayLayer.cs:line 430
   at Vintagestory.GameContent.GuiDialogWorldMap.Open_Patch2(GuiDialogWorldMap this, EnumDialogType type)
   at Vintagestory.GameContent.WorldMapManager.ToggleMap(EnumDialogType asType) in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 306
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 220
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 372
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1040
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\caucow\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"
```

**Comment by Wooza** [comment]
You are right. It seems that even older version of the ProspectorInfo files did not even have a Values attribute. I have adjusted the import logic to handle this case and uploaded a new version.
